In [ ]:
import pandas as pd

csv_path = "../data/raw/Comprehensive_Banking_Database.csv"

df = pd.read_csv(csv_path)

#display(df.shape)
#display(df.columns)
#display(df.info())

clients_cols = [
    "Customer ID",
    "First Name",
    "Last Name",
    "Age",
    "Gender",
    "City",
    "Date Of Account Opening",
]

clients_df = df[clients_cols].drop_duplicates(subset=["Customer ID"])
#clients_df.head()

clients_df = clients_df.rename(columns={
    "Customer ID": "client_id",
    "First Name": "first_name",
    "Last Name": "last_name",
    "Age": "age",
    "Gender": "gender",
    "City": "city",
    "Date Of Account Opening": "account_opening_date",
})

display(clients_df.head())

accounts_cols = [
    "Customer ID",
    "Account Type",
    "Account Balance",
    "Branch ID",
    "Date Of Account Opening",
]

accounts_df = df[accounts_cols].drop_duplicates(subset=["Customer ID", "Account Type"])

accounts_df["account_id"] = (
    accounts_df["Customer ID"].astype(str) + "_" + accounts_df["Account Type"].astype(str)
)

accounts_df = accounts_df.rename(columns={
    "Customer ID": "client_id",
    "Account Type": "account_type",
    "Account Balance": "account_balance",
    "Branch ID": "branch_code",
    "Date Of Account Opening": "opening_date",
})

accounts_df = accounts_df[[
    "account_id",
    "client_id",
    "account_type",
    "branch_code",
    "account_balance",
    "opening_date",
]]

display(accounts_df.head())

,client_id,first_name,last_name,age,gender,city,account_opening_date
0,1,Joshua,Hall,45,Male,Fort Worth,5/26/2006
1,2,Mark,Taylor,47,Female,Louisville,3/2/2006
2,3,Joseph,Flores,25,Female,Philadelphia,7/19/2015
3,4,Kevin,Lee,52,Other,Oklahoma City,1/30/2008
4,5,Linda,Johnson,68,Other,Phoenix,5/25/2021

,account_id,client_id,account_type,branch_code,account_balance,opening_date
0,1_Current,1,Current,43,1313.38,5/26/2006
1,2_Current,2,Current,63,5988.46,3/2/2006
2,3_Current,3,Current,82,8277.88,7/19/2015
3,4_Savings,4,Savings,41,7487.21,1/30/2008
4,5_Savings,5,Savings,9,6993.55,5/25/2021